#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.

TOTAL_STAGES=6

banner "发布 dsh-mattpocock-skills-deck v1.7.3 到 npm（官方源）"

# ── Stage 1: 前置三查 ────────────────────────────────────────────────────────
stage "前置三查 — 环境 / 登录态 / 包名 / 源"
say "本向导将把 package/ 目录的 1.7.3 发布到官方源，并确认 latest 变为 1.7.3。"
say "官方源 https://registry.npmjs.org 与镜像不同步时，只有官方源的 latest 才算数。"
note "包名 dsh-mattpocock-skills-deck 已存在；发同名同版本会 E409，需升版（本次 1.7.3 未占用，可直接发）。"
echo ""
say "自动检查："
node -v
npm -v
echo "registry (npm config get): $(npm config get registry)"
echo -n "npm whoami (官方源): "
if npm whoami --registry=https://registry.npmjs.org 2>/tmp/whoami.txt; then
  echo "已登录：$(cat /tmp/whoami.txt)"
else
  echo "未登录（401）— 下一阶段会引导登录"
  cat /tmp/whoami.txt | sed 's/^/    /'
fi
echo -n "npm view latest (官方源 --prefer-online): "
LATEST=$(npm view dsh-mattpocock-skills-deck version --registry=https://registry.npmjs.org --prefer-online 2>&1 | tail -n1)
if [ "$LATEST" = "1.7.2" ]; then
  echo "1.7.2（符合预期，1.7.3 待发布）"
elif [ "$LATEST" = "1.7.3" ]; then
  echo "1.7.3（已是最新，无需再发）"
else
  echo "$LATEST"
fi
echo "本地 package/package.json version: $(grep -o '"version":[^,]*' package/package.json | head -n1)"
warn "若 npm config registry 指向 npmmirror，发布时必须显式 --registry=https://registry.npmjs.org（本向导所有发布命令已带该参数）"
pause "检查完毕，回车进入打包预览"

# ── Stage 2: 打包预览 ────────────────────────────────────────────────────────
stage "打包预览 — 只发 63 个白名单文件"
say "package/package.json 的 files=[lib,shared,cordis.patch.yml] 是白名单；测试、文档、密钥绝不进包。"
step "将在 package/ 目录执行 npm pack --dry-run 并展示 Tarball Contents"
note "预期：63 文件（lib/* + shared/* + cordis.patch.yml + README + package.json），371 kB 级，无 node_modules/.env"
if confirm "现在执行打包预览？"; then
  echo ""
  (cd package && npm pack --dry-run --registry=https://registry.npmjs.org 2>&1 | sed 's/^/  /')
  echo ""
  if confirm "预览内容只含预期 63 文件且无多余密钥/文档？（干净才继续）"; then
    note "预览通过。"
  else
    warn "预览未通过 — 请先修正 package/package.json 的 files 白名单或清理多余文件，再重跑本向导。"
    exit 1
  fi
else
  warn "已跳过预览 — 强烈建议回头补跑：(cd package && npm pack --dry-run)"
  pause "回车继续（不推荐）"
fi

# ── Stage 3: 登录 ───────────────────────────────────────────────────────────
stage "登录 npm（官方源，网页 2FA）"
say "发布必须先在官方源登录；镜像源的登录不算数。"
if npm whoami --registry=https://registry.npmjs.org >/dev/null 2>&1; then
  echo "已登录：$(npm whoami --registry=https://registry.npmjs.org 2>&1)"
  if confirm "已登录，是否跳过登录步骤？"; then
    note "跳过登录。"
  else
    say "将重新执行 npm login --auth-type=web（浏览器授权）"
    echo ""
    npm login --auth-type=web --registry=https://registry.npmjs.org
    echo ""
    say "再次校验登录："
    npm whoami --registry=https://registry.npmjs.org
    pause "登录完成后回车继续"
  fi
else
  warn "当前未登录（E401）— 需要浏览器完成授权 + 2FA"
  say "将执行：npm login --auth-type=web --registry=https://registry.npmjs.org"
  note "终端会打印 Authenticate your account at: https://www.npmjs.com/auth/cli/<uuid>"
  step "按回车 → 浏览器打开授权页 → 完成登录 + 2FA（或恢复码填进 2FA 框）→ 回终端按回车"
  open_url "https://www.npmjs.com/login"
  echo ""
  if confirm "准备好后开始登录？"; then
    npm login --auth-type=web --registry=https://registry.npmjs.org
    echo ""
    say "校验："
    npm whoami --registry=https://registry.npmjs.org && echo "登录成功" || warn "仍未登录，请重跑本阶段"
  else
    warn "已跳过登录 — 下一阶段的 publish 会报 ENEEDAUTH"
  fi
  pause "回车进入发布阶段"
fi

# ── Stage 4: 发布 ───────────────────────────────────────────────────────────
stage "发布 — 交互式终端 + 浏览器 2FA 审批"
warn "关键约束：发布命令不要重定向输出（> file 会让 stdout 非 TTY 而触发 EOTP）"
say "将在可交互终端执行：(cd package && npm publish --registry=https://registry.npmjs.org)"
note "账号开启 2FA 时会打印：Authenticate your account at: https://www.npmjs.com/auth/cli/<uuid>"
step "按回车 → 浏览器自动打开授权页 → 完成 2FA 审批 → 回终端按回车 → 出现 + dsh-mattpocock-skills-deck@1.7.3 即成功"
echo ""
say "备选：若你偏好一次性码，可在认证器 App 复制 6 位码后改用：npm publish --otp=<code> --registry=https://registry.npmjs.org"
open_url "https://www.npmjs.com/package/dsh-mattpocock-skills-deck"
echo ""
if confirm "现在执行发布？（需在有 TTY 的终端，不要在后台 job）"; then
  (cd package && npm publish --registry=https://registry.npmjs.org --auth-type=web 2>&1 | tee /tmp/npm-publish.log; echo "EXIT_CODE:$?" >> /tmp/npm-publish.log)
  PUB_EXIT=$(grep -o "EXIT_CODE:[0-9]*" /tmp/npm-publish.log | tail -n1 | cut -d: -f2)
  cat /tmp/npm-publish.log | sed 's/^/  /'
  if grep -q "dsh-mattpocock-skills-deck@1.7.3" /tmp/npm-publish.log; then
    echo "发布成功：+ dsh-mattpocock-skills-deck@1.7.3"
  elif grep -q "already.*published" /tmp/npm-publish.log || grep -q "E409" /tmp/npm-publish.log; then
    warn "版本重复（E403/E409）：1.7.3 已在官方源存在，需升 version 再发"
  elif grep -q "E401" /tmp/npm-publish.log || grep -q "ENEEDAUTH" /tmp/npm-publish.log; then
    warn "未登录（E401/ENEEDAUTH）：回第 3 阶段重新登录"
  elif grep -q "EOTP" /tmp/npm-publish.log; then
    warn "EOTP：非交互环境或输出被重定向。请在有 TTY 的 PowerShell/终端手跑：cd package && npm publish --registry=https://registry.npmjs.org --auth-type=web"
  else
    if [ "$PUB_EXIT" = "0" ]; then
      echo "发布命令退出 0，请结合上方是否出现 + 包@版本 判断"
    else
      warn "发布未成功（exit $PUB_EXIT），请按上表对照报错码处理"
    fi
  fi
else
  warn "已跳过发布 — 可稍后在交互终端手跑：cd package && npm publish --registry=https://registry.npmjs.org --auth-type=web"
fi
pause "回车进入验证阶段"

# ── Stage 5: 验证 ───────────────────────────────────────────────────────────
stage "验证 — 官方源最新版与可安装性"
say "验证必须显式 --registry=https://registry.npmjs.org 并 --prefer-online 跳过本地缓存"
echo -n "npm view dsh-mattpocock-skills-deck version --prefer-online: "
VER=$(npm view dsh-mattpocock-skills-deck version --registry=https://registry.npmjs.org --prefer-online 2>&1 | tail -n1)
echo "$VER"
if [ "$VER" = "1.7.3" ]; then
  echo "最新版已是 1.7.3（发布成功）"
elif [ "$VER" = "1.7.2" ]; then
  echo "仍为 1.7.2（1.7.3 未到达官方源，请检查发布是否成功）"
else
  echo "当前 latest: $VER"
fi
echo ""
echo "npm view dist-tags (官方源): "
npm view dsh-mattpocock-skills-deck dist-tags --registry=https://registry.npmjs.org --json 2>&1 | sed 's/^/  /'
echo ""
echo "包主页："
open_url "https://www.npmjs.com/package/dsh-mattpocock-skills-deck"
echo ""
echo "可选：临时目录试装（验证包可被下载安装）"
if confirm "是否现在做临时试装？（mkdir /tmp/npm-verify && npm install dsh-mattpocock-skills-deck --registry=https://registry.npmjs.org）"; then
  TMPDIR=$(mktemp -d 2>/dev/null || mktemp -d -t npm-verify)
  (cd "$TMPDIR" && npm install dsh-mattpocock-skills-deck --registry=https://registry.npmjs.org 2>&1 | sed 's/^/  /')
  echo "试装目录：$TMPDIR"
  note "试装完成即证明包已可在官方源被拉取"
else
  note "已跳过试装 — 可稍后手动验证"
fi
pause "回车查看收尾说明"

# ── Stage 6: 收尾 ───────────────────────────────────────────────────────────
stage "收尾 — DSH 侧生效与回滚预案"
say "npm 官方源发布后，DSH 桌面端的 pnpm 供应链策略 minimumReleaseAge 会让 dsh plugin update 数小时内静默忽略新版（不报错也不更新）"
step "验证后请告知用户显式更新：dsh plugin --profile web add dsh-mattpocock-skills-deck@1.7.3 --registry https://registry.npmjs.org"
step "并提醒：完全退出 DSH 再重开 + Ctrl+F5 刷新页面才能看到新版本（右下角 DSW_VERSION=v1.7.3）"
echo ""
say "撤回预案（慎用，发布时间 = 公开）："
note "72 小时内可 npm unpublish dsh-mattpocock-skills-deck@1.7.3 --registry=https://registry.npmjs.org（但历史记录保留，重发同版本仍可能 E409，需升版）"
note "超 72 小时只能 npm deprecate dsh-mattpocock-skills-deck@1.7.3 \"reason\" --registry=https://registry.npmjs.org 标记废弃"
echo ""
say "令牌安全：本次登录的令牌已写入 npm 本地配置；若泄露立即到 https://www.npmjs.com/settings/feather_wch/tokens 吊销"
finish