import { describe, expect, it } from 'vitest'
import { assertWireIdentityInvariant } from 'dsh-antigravity-auth/invariant'
import { DSH_ATTRIBUTION_HEADER, createWireIdentity } from 'dsh-antigravity-auth/wire-identity'

describe('Wire Identity invariant', () => {
  it('accepts the immutable identity generated by the public module', () => {
    const headers = createWireIdentity().headers()
    expect(() => assertWireIdentityInvariant(headers)).not.toThrow()
  })

  it('rejects a missing or replaced secondary carrier', () => {
    const headers = { ...createWireIdentity().headers() }
    delete (headers as Record<string, string>)[DSH_ATTRIBUTION_HEADER]
    try {
      assertWireIdentityInvariant(headers)
      expect.fail('expected the invariant to reject the missing carrier')
    } catch (error) {
      expect(error).toMatchObject({ code: 'WIRE_IDENTITY_INVARIANT' })
    }
  })
})
